# Generated by Django 3.2.3 on 2021-05-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradepost',
            name='end_date',
            field=models.DateField(),
        ),
    ]
