# Generated by Django 3.2.3 on 2021-05-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0002_alter_tradepost_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradepost',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
