# Generated by Django 3.2.3 on 2021-05-20 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tradeapp', '0003_alter_tradepost_posted_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiddingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_product_price', models.FloatField(default=0.0)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('bid_product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tradeapp.tradepost')),
                ('bid_publisher_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
