# Generated by Django 3.2.3 on 2021-05-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradeapp', '0004_biddingpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddingpost',
            name='bid_publisher_name',
            field=models.CharField(max_length=200),
        ),
    ]
